version     = '0.0.2'
hosts_file  = '/etc/hosts'
socket_file = '/tmp/focusd.sock'
pid_file    = '/tmp/focusd.pid'

blocked = [
    'news.ycombinator.com',
    'youtube.com',
    'facebook.com',
    'reddit.com',
    'xkcd.com',
    'smbc-comics.com',
    'netflix.com'
]
